# ==================================================
# Calculating eDNA indices of abundance
# input data generated by Ramon Gallego @
# https://github.com/ramongallego/eDNA.and.Ocean.Acidification.Gallego.et.al.2020
# Last updated 04/26/2021
# TODO: Needs some QA from Ryan and/or Moncho 
# ==================================================
library('tidyverse')
library('dplyr')

hash.annotated <- read.csv('../data/hash.annotated.csv') # Mocho's hashes with taxa info
events <- read.csv('../data/events.joe.format.csv') # Moncho's event/environmental params w/ dates reformatted
ASV.table <- read.csv('../data/ASV_table_all_together.csv') # miseq run number, hash, sample, nReads
taxonomy.table <- read.csv('../data/all.taxonomy.20190130.csv') # hash with taxa info, total reads, total reps?, total sites present

# get table with sample, nReads, hash, and taxa information - why do we lose hashes here? 
ASV.tax <- inner_join(ASV.table, taxonomy.table)

# ==================================================
# This is the step I am least confident in
# merge replicates
# ==================================================
by.hash.sample.w.reps <- ASV.tax %>%
  group_by(sample, species, Hash) %>% # group the columns you want to "leave alone"
  summarize(nReads=sum(nReads)) %>% # sum nReads
  separate(col=sample, into=c('sample','tech'), sep='[.]') %>% # make technical and biological reps into columns
  separate(col=sample, into=c("sample", "bio"), sep = 9) # so that I can merge them

by.hash.sample <- by.hash.sample.w.reps %>%
  group_by(sample, species, Hash) %>%
  summarize(nReads=sum(nReads)) # same summarize code as used above - is this correct? 

# ==================================================
# by.hash.sample has separate rows for ASVs that are the same taxa/species but different hash
# now I want to merge these so all ASVs for a taxa/species are grouped 
# ==================================================
by.sample.species <- by.hash.sample %>%
  group_by(sample, species) %>% 
  summarize(nReads=sum(nReads))

write.csv(by.sample.species,"../data/by.sample.species.csv")

# ==================================================
# begin calculating inputs needed for eDNA index 
# ***max number of reads per sample*** - SHOULD THIS BE BASED ON A SINGLE HASH or SINGLE SPECIES? 
# ==================================================
maxreads_j.HASH <- by.hash.sample %>%
  group_by(sample) %>%
  summarize(max_j=max(nReads))

# i think the above is correct, the below is incorrect - confirm with Ryan/Moncho
maxreads_j.SPECIES <- by.sample.species %>%
  group_by(sample) %>%
  summarize(max_j=max(nReads))

# calculate ***total reads by species***
nreads_i <- by.sample.species %>%
  group_by(species) %>%
  summarize(Y_i=sum(nReads)) 

# ==================================================
# put together joint table to calculate eDNA index 
# ==================================================
eDNA <- inner_join(by.sample.species, nreads_i)
eDNA <- inner_join(eDNA, maxreads_j.HASH)

# actual eDNA index calculations, there is probably a way to make this more readable with tidyverse, sorry Ryan!
# formula @ https://www.nature.com/articles/s41598-019-48546-x
eDNA$index <- (eDNA$nReads/eDNA$Y_i)/eDNA$max_j*(eDNA$nReads/eDNA$Y_i)
eDNA$log.index <- log(eDNA$index)


# ==================================================
# ==================================================
# create useful table with just the taxa that Moncho classified as BENTHIC
# merge hashes by species
# ==================================================
species.annotated <- hash.annotated %>%
  distinct(species, .keep_all=TRUE) 

ben.community <- inner_join(species.annotated, by.sample.species)